export const projects = [
  {
    title: 'Asian Flags',
    description: "An App made with simple React.js that loads Asian Flags without taking time",
      image: '/images/1.png',
      tags: ['React.js'],
    source: '#',
    visit: 'https://aarish-rajput.github.io/asian-flags/',
    id: 0,
  },
  {
    title: 'Github Searcher',
    description:"Github Searcher is the app made with React.js styled with Bootstrap that searches Github users and displays their details",
    image: '/images/2.png',
    tags: ['React', 'GitHub API'],
    source: 'https://google.com',
    visit: 'https://aarish-rajput.github.io/github-searcher/',
    id: 1,
  },
  {
    title: 'Intouch',
    description: "It is a Full Stack MERN App styled with Materlize CSS that is like social media App with Authentication with JWT",
    image: '/images/3.png',
    tags: ['React', 'Node.js', 'Express.js','MongoDB'],
    source: 'https://google.com',
    visit: 'http://in-touch27.herokuapp.com/',
    id: 2,
  },
  {
    title: 'BlueShop',
    description: "It is a Full Stack MERN Ecommerce App with basic functionalities of Ecommerce App",
    image: '/images/4.png',
    tags: ['React', 'Node.js', 'Express.js','MongoDB'],
    source: 'https://google.com',
    visit: 'http://blueshop27.herokuapp.com/',
    id: 3,
  },
   {
    title: 'MoviesFun',
    description: "It is a movie app and it gives information about new and popular movies and it is made with Next.js, tmbd API and tailwindcss",
    image: '/images/5.png',
    tags: ['Next.js', 'tmbd API'],
    source: 'https://google.com',
    visit: 'https://movies-fun.vercel.app/',
    id: 4,
  },
    {
    title: 'React Admin UI',
    description: "It is user interface of React Admin UI, recharts and it is made with React.js and Material UI",
    image: '/images/6.png',
    tags: ['React.js', 'Recharts'],
    source: 'https://google.com',
    visit: 'https://aarish-rajput.github.io/react-admin-ui/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my programmnig journey and Graduation', },
  { year: 2019, text: 'Started basics of web development', },
  { year: 2020, text: ' Completed my graducation and strated Masters', },
  { year: 2021, text: 'Started learning advance web development', },
  { year: 2022, text: 'Completed my masters', },
];